name: Update gist with WakaTime stats 2
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: taylorhutchison/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 3a9e8cb2c793896d21bbf196646c627d
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
